### ISSUE TITLE
[BUG]: Plotting crashes due to array shape error

### ISSUE THREAD

**Issue by ljlamarche** [amisr/resolvedvelocities#14]
When running resolvedvelocities on PFISR experiment 20141002.003, the program crashes while attempting to create magnitude plots with the following error:

```
Traceback (most recent call last):
  File "/anaconda2/envs/python3.6/bin/resolvedvelocities", line 33, in <module>
    sys.exit(load_entry_point('resolvedvelocities', 'console_scripts', 'resolvedvelocities')())
  File "/Users/e30737/Desktop/Projects/AMISR/resolvedvelocities/resolvedvelocities/run_resolve_vectors.py", line 94, in main
    rv.create_plots()
  File "/Users/e30737/Desktop/Projects/AMISR/resolvedvelocities/resolvedvelocities/ResolveVectors.py", line 769, in create_plots
    day_ind=t)
  File "/Users/e30737/Desktop/Projects/AMISR/resolvedvelocities/resolvedvelocities/plot/summary_plots.py", line 173, in plot_magnitude
    inds = np.where(cond1 | cond2 | cond3)
ValueError: operands could not be broadcast together with shapes (491,15) (494,15)
```

**Comment by ljlamarche** [comment]
Solved with #15.
